version: '3.9'

services:
  postgres_dev:
    image: postgres
    container_name: postgres_dev
    ports:
      - '5434:5432'
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - 'postgres_dev:/var/lib/postgresql/data'

volumes:
  postgres_dev: